version: '3'
services:
    brat:
        build: .
        volumes:
            - ./shared:/shared
        expose:
            - 8080
        environment:
            VIRTUAL_HOST: brat.theorizeit.org
            VIRTUAL_PORT: 8080
            #LETSENCRYPT_HOST: brat.theorizeit.org
            #LETSENCRYPT_EMAIL: dave@daveeargle.com
networks:
    default:
        external:
            name: nginx-proxy